#ifndef MaPLSymbols_h
#define MaPLSymbols_h
enum MaPLSymbols {
    MaPLSymbols_ArrayMap_contains_string = 1,
    MaPLSymbols_Array_count = 2,
    MaPLSymbols_GLOBAL_commandLineFlagEnabled_string = 3,
    MaPLSymbols_GLOBAL_executeMaPLScript_string = 4,
    MaPLSymbols_GLOBAL_hash_string = 5,
    MaPLSymbols_GLOBAL_outputToFile_string = 6,
    MaPLSymbols_GLOBAL_pluralize_string = 7,
    MaPLSymbols_GLOBAL_schema = 8,
    MaPLSymbols_GLOBAL_writeToFile_VARIADIC = 9,
    MaPLSymbols_GLOBAL_xmlFiles = 10,
    MaPLSymbols_SchemaAttribute_annotations = 11,
    MaPLSymbols_SchemaAttribute_defaultValues = 12,
    MaPLSymbols_SchemaAttribute_isPrimitiveType = 13,
    MaPLSymbols_SchemaAttribute_maxOccurrences = 14,
    MaPLSymbols_SchemaAttribute_minOccurrences = 15,
    MaPLSymbols_SchemaAttribute_name = 16,
    MaPLSymbols_SchemaAttribute_typeIsUIDReference = 17,
    MaPLSymbols_SchemaAttribute_typeName = 18,
    MaPLSymbols_SchemaClass_annotations = 19,
    MaPLSymbols_SchemaClass_attributes = 20,
    MaPLSymbols_SchemaClass_name = 21,
    MaPLSymbols_SchemaClass_superclass = 22,
    MaPLSymbols_SchemaEnum_annotations = 23,
    MaPLSymbols_SchemaEnum_cases = 24,
    MaPLSymbols_SchemaEnum_name = 25,
    MaPLSymbols_Schema_classes = 26,
    MaPLSymbols_Schema_enums = 27,
    MaPLSymbols_XMLAttribute_name = 28,
    MaPLSymbols_XMLAttribute_value = 29,
    MaPLSymbols_XMLFile_outputPath = 30,
    MaPLSymbols_XMLFile_rootNode = 31,
    MaPLSymbols_XMLNode_attributes = 32,
    MaPLSymbols_XMLNode_children = 33,
    MaPLSymbols_XMLNode_name = 34,
};
#endif /* MaPLSymbols_h */
