#ifndef MaPLSymbols_h
#define MaPLSymbols_h
enum MaPLSymbols {
    MaPLSymbols_ArrayMap_contains_string = 1,
    MaPLSymbols_Array_count = 2,
    MaPLSymbols_GLOBAL_commandLineFlag_string = 3,
    MaPLSymbols_GLOBAL_executeMaPLScript_string = 4,
    MaPLSymbols_GLOBAL_hash_string = 5,
    MaPLSymbols_GLOBAL_outputToFile_string = 6,
    MaPLSymbols_GLOBAL_pluralize_string = 7,
    MaPLSymbols_GLOBAL_schemas = 8,
    MaPLSymbols_GLOBAL_writeToFile_VARIADIC = 9,
    MaPLSymbols_GLOBAL_xmlFiles = 10,
    MaPLSymbols_SchemaAttribute_annotations = 11,
    MaPLSymbols_SchemaAttribute_defaultValues = 12,
    MaPLSymbols_SchemaAttribute_isPrimitiveType = 13,
    MaPLSymbols_SchemaAttribute_maxOccurrences = 14,
    MaPLSymbols_SchemaAttribute_minOccurrences = 15,
    MaPLSymbols_SchemaAttribute_name = 16,
    MaPLSymbols_SchemaAttribute_typeIsUIDReference = 17,
    MaPLSymbols_SchemaAttribute_typeName = 18,
    MaPLSymbols_SchemaAttribute_typeNamespace = 19,
    MaPLSymbols_SchemaClass_annotations = 20,
    MaPLSymbols_SchemaClass_attributes = 21,
    MaPLSymbols_SchemaClass_name = 22,
    MaPLSymbols_SchemaClass_superclass = 23,
    MaPLSymbols_SchemaClass_superclassNamespace = 24,
    MaPLSymbols_SchemaEnum_annotations = 25,
    MaPLSymbols_SchemaEnum_cases = 26,
    MaPLSymbols_SchemaEnum_name = 27,
    MaPLSymbols_Schema_classes = 28,
    MaPLSymbols_Schema_enums = 29,
    MaPLSymbols_Schema_namespace = 30,
    MaPLSymbols_XMLAttribute_name = 31,
    MaPLSymbols_XMLAttribute_value = 32,
    MaPLSymbols_XMLNode_attributes = 33,
    MaPLSymbols_XMLNode_children = 34,
    MaPLSymbols_XMLNode_name = 35,
    MaPLSymbols_XMLNode_namespace = 36,
};
#endif /* MaPLSymbols_h */
