#ifndef MaPLSymbols_h
#define MaPLSymbols_h
enum MaPLSymbols {
    MaPLSymbols_ArrayMap_contains_string = 1,
    MaPLSymbols_Array_count = 2,
    MaPLSymbols_GLOBAL_commandLineFlag_string = 3,
    MaPLSymbols_GLOBAL_executeMaPLScript_string = 4,
    MaPLSymbols_GLOBAL_hash_string = 5,
    MaPLSymbols_GLOBAL_inParameters = 6,
    MaPLSymbols_GLOBAL_outParameters = 7,
    MaPLSymbols_GLOBAL_outputToFile_string = 8,
    MaPLSymbols_GLOBAL_schemas = 9,
    MaPLSymbols_GLOBAL_writeToFile_VARIADIC = 10,
    MaPLSymbols_GLOBAL_xmlFiles = 11,
    MaPLSymbols_SchemaAttribute_annotations = 12,
    MaPLSymbols_SchemaAttribute_defaultValues = 13,
    MaPLSymbols_SchemaAttribute_maxOccurrences = 14,
    MaPLSymbols_SchemaAttribute_minOccurrences = 15,
    MaPLSymbols_SchemaAttribute_name = 16,
    MaPLSymbols_SchemaAttribute_typeIsClass = 17,
    MaPLSymbols_SchemaAttribute_typeIsEnum = 18,
    MaPLSymbols_SchemaAttribute_typeIsUIDReference = 19,
    MaPLSymbols_SchemaAttribute_typeName = 20,
    MaPLSymbols_SchemaAttribute_typeNamespace = 21,
    MaPLSymbols_SchemaClass_annotations = 22,
    MaPLSymbols_SchemaClass_attributes = 23,
    MaPLSymbols_SchemaClass_name = 24,
    MaPLSymbols_SchemaClass_superclass = 25,
    MaPLSymbols_SchemaClass_superclassNamespace = 26,
    MaPLSymbols_SchemaEnum_annotations = 27,
    MaPLSymbols_SchemaEnum_cases = 28,
    MaPLSymbols_SchemaEnum_name = 29,
    MaPLSymbols_Schema_classes = 30,
    MaPLSymbols_Schema_enums = 31,
    MaPLSymbols_Schema_namespace = 32,
    MaPLSymbols_XMLAttribute_name = 33,
    MaPLSymbols_XMLAttribute_value = 34,
    MaPLSymbols_XMLAttribute_values = 35,
    MaPLSymbols_XMLNode_attributes = 36,
    MaPLSymbols_XMLNode_children = 37,
    MaPLSymbols_XMLNode_name = 38,
    MaPLSymbols_XMLNode_namespace = 39,
};
#endif /* MaPLSymbols_h */
