//
//  MaPLBytecodeConstants.h
//
//  Created by Brad Bambara on 2/5/22.
//

#ifndef MaPLBytecodeConstants_h
#define MaPLBytecodeConstants_h

// Byte sizes for MaPL bytecode.
typedef u_int8_t MaPLParameterCount;
typedef u_int16_t MaPLMemoryAddress;
typedef u_int16_t MaPLCursorMove;
typedef u_int16_t MaPLSymbol;
typedef u_int16_t MaPLLineNumber;

// Bytecodes are sorted by return type.
enum MaPLInstruction : u_int8_t {
    MaPLInstruction_placeholder = 0,
    
    // INT32
    MaPLInstruction_int32_literal = 1,
    MaPLInstruction_int32_variable = 2,
    MaPLInstruction_int32_add = 3,
    MaPLInstruction_int32_subtract = 4,
    MaPLInstruction_int32_divide = 5,
    MaPLInstruction_int32_multiply = 6,
    MaPLInstruction_int32_modulo = 7,
    MaPLInstruction_int32_numeric_negation = 8,
    MaPLInstruction_int32_bitwise_and = 9,
    MaPLInstruction_int32_bitwise_or = 10,
    MaPLInstruction_int32_bitwise_xor = 11,
    MaPLInstruction_int32_bitwise_negation = 12,
    MaPLInstruction_int32_bitwise_shift_left = 13,
    MaPLInstruction_int32_bitwise_shift_right = 14,
    MaPLInstruction_int32_function_invocation = 15,
    MaPLInstruction_int32_subscript_invocation = 16,
    MaPLInstruction_int32_ternary_conditional = 17,
    MaPLInstruction_int32_typecast = 18,
    
    // FLOAT32
    MaPLInstruction_float32_literal = 19,
    MaPLInstruction_float32_variable = 20,
    MaPLInstruction_float32_add = 21,
    MaPLInstruction_float32_subtract = 22,
    MaPLInstruction_float32_divide = 23,
    MaPLInstruction_float32_multiply = 24,
    MaPLInstruction_float32_modulo = 25,
    MaPLInstruction_float32_numeric_negation = 26,
    MaPLInstruction_float32_function_invocation = 27,
    MaPLInstruction_float32_subscript_invocation = 28,
    MaPLInstruction_float32_ternary_conditional = 29,
    MaPLInstruction_float32_typecast = 30,
    
    // STRING
    MaPLInstruction_string_literal = 31,
    MaPLInstruction_string_variable = 32,
    MaPLInstruction_string_concat = 33,
    MaPLInstruction_string_function_invocation = 34,
    MaPLInstruction_string_subscript_invocation = 35,
    MaPLInstruction_string_ternary_conditional = 36,
    MaPLInstruction_string_typecast = 37,
    MaPLInstruction_string_typecast_from_pointer = 38,
    
    // POINTER
    MaPLInstruction_literal_null = 39,
    MaPLInstruction_pointer_variable = 40,
    MaPLInstruction_pointer_null_coalescing = 41,
    MaPLInstruction_pointer_function_invocation = 42,
    MaPLInstruction_pointer_subscript_invocation = 43,
    MaPLInstruction_pointer_ternary_conditional = 44,
    
    // BOOLEAN
    MaPLInstruction_literal_true = 45,
    MaPLInstruction_literal_false = 46,
    MaPLInstruction_boolean_variable = 47,
    MaPLInstruction_boolean_function_invocation = 48,
    MaPLInstruction_boolean_subscript_invocation = 49,
    MaPLInstruction_boolean_ternary_conditional = 50,
    MaPLInstruction_boolean_typecast = 51,
    MaPLInstruction_logical_equality_char = 52,
    MaPLInstruction_logical_equality_int32 = 53,
    MaPLInstruction_logical_equality_int64 = 54,
    MaPLInstruction_logical_equality_uint32 = 55,
    MaPLInstruction_logical_equality_uint64 = 56,
    MaPLInstruction_logical_equality_float32 = 57,
    MaPLInstruction_logical_equality_float64 = 58,
    MaPLInstruction_logical_equality_boolean = 59,
    MaPLInstruction_logical_equality_string = 60,
    MaPLInstruction_logical_equality_pointer = 61,
    MaPLInstruction_logical_inequality_char = 62,
    MaPLInstruction_logical_inequality_int32 = 63,
    MaPLInstruction_logical_inequality_int64 = 64,
    MaPLInstruction_logical_inequality_uint32 = 65,
    MaPLInstruction_logical_inequality_uint64 = 66,
    MaPLInstruction_logical_inequality_float32 = 67,
    MaPLInstruction_logical_inequality_float64 = 68,
    MaPLInstruction_logical_inequality_boolean = 69,
    MaPLInstruction_logical_inequality_string = 70,
    MaPLInstruction_logical_inequality_pointer = 71,
    MaPLInstruction_logical_less_than_char = 72,
    MaPLInstruction_logical_less_than_int32 = 73,
    MaPLInstruction_logical_less_than_int64 = 74,
    MaPLInstruction_logical_less_than_uint32 = 75,
    MaPLInstruction_logical_less_than_uint64 = 76,
    MaPLInstruction_logical_less_than_float32 = 77,
    MaPLInstruction_logical_less_than_float64 = 78,
    MaPLInstruction_logical_less_than_equal_char = 79,
    MaPLInstruction_logical_less_than_equal_int32 = 80,
    MaPLInstruction_logical_less_than_equal_int64 = 81,
    MaPLInstruction_logical_less_than_equal_uint32 = 82,
    MaPLInstruction_logical_less_than_equal_uint64 = 83,
    MaPLInstruction_logical_less_than_equal_float32 = 84,
    MaPLInstruction_logical_less_than_equal_float64 = 85,
    MaPLInstruction_logical_greater_than_char = 86,
    MaPLInstruction_logical_greater_than_int32 = 87,
    MaPLInstruction_logical_greater_than_int64 = 88,
    MaPLInstruction_logical_greater_than_uint32 = 89,
    MaPLInstruction_logical_greater_than_uint64 = 90,
    MaPLInstruction_logical_greater_than_float32 = 91,
    MaPLInstruction_logical_greater_than_float64 = 92,
    MaPLInstruction_logical_greater_than_equal_char = 93,
    MaPLInstruction_logical_greater_than_equal_int32 = 94,
    MaPLInstruction_logical_greater_than_equal_int64 = 95,
    MaPLInstruction_logical_greater_than_equal_uint32 = 96,
    MaPLInstruction_logical_greater_than_equal_uint64 = 97,
    MaPLInstruction_logical_greater_than_equal_float32 = 98,
    MaPLInstruction_logical_greater_than_equal_float64 = 99,
    MaPLInstruction_logical_and = 100,
    MaPLInstruction_logical_or = 101,
    MaPLInstruction_logical_negation = 102,
    
    // INT64
    MaPLInstruction_int64_literal = 103,
    MaPLInstruction_int64_variable = 104,
    MaPLInstruction_int64_add = 105,
    MaPLInstruction_int64_subtract = 106,
    MaPLInstruction_int64_divide = 107,
    MaPLInstruction_int64_multiply = 108,
    MaPLInstruction_int64_modulo = 109,
    MaPLInstruction_int64_numeric_negation = 110,
    MaPLInstruction_int64_bitwise_and = 111,
    MaPLInstruction_int64_bitwise_or = 112,
    MaPLInstruction_int64_bitwise_xor = 113,
    MaPLInstruction_int64_bitwise_negation = 114,
    MaPLInstruction_int64_bitwise_shift_left = 115,
    MaPLInstruction_int64_bitwise_shift_right = 116,
    MaPLInstruction_int64_function_invocation = 117,
    MaPLInstruction_int64_subscript_invocation = 118,
    MaPLInstruction_int64_ternary_conditional = 119,
    MaPLInstruction_int64_typecast = 120,
    
    // FLOAT64
    MaPLInstruction_float64_literal = 121,
    MaPLInstruction_float64_variable = 122,
    MaPLInstruction_float64_add = 123,
    MaPLInstruction_float64_subtract = 124,
    MaPLInstruction_float64_divide = 125,
    MaPLInstruction_float64_multiply = 126,
    MaPLInstruction_float64_modulo = 127,
    MaPLInstruction_float64_numeric_negation = 128,
    MaPLInstruction_float64_function_invocation = 129,
    MaPLInstruction_float64_subscript_invocation = 130,
    MaPLInstruction_float64_ternary_conditional = 131,
    MaPLInstruction_float64_typecast = 132,
    
    // UINT32
    MaPLInstruction_uint32_literal = 133,
    MaPLInstruction_uint32_variable = 134,
    MaPLInstruction_uint32_add = 135,
    MaPLInstruction_uint32_subtract = 136,
    MaPLInstruction_uint32_divide = 137,
    MaPLInstruction_uint32_multiply = 138,
    MaPLInstruction_uint32_modulo = 139,
    MaPLInstruction_uint32_bitwise_and = 140,
    MaPLInstruction_uint32_bitwise_or = 141,
    MaPLInstruction_uint32_bitwise_xor = 142,
    MaPLInstruction_uint32_bitwise_negation = 143,
    MaPLInstruction_uint32_bitwise_shift_left = 144,
    MaPLInstruction_uint32_bitwise_shift_right = 145,
    MaPLInstruction_uint32_function_invocation = 146,
    MaPLInstruction_uint32_subscript_invocation = 147,
    MaPLInstruction_uint32_ternary_conditional = 148,
    MaPLInstruction_uint32_typecast = 149,
    
    // UINT64
    MaPLInstruction_uint64_literal = 150,
    MaPLInstruction_uint64_variable = 151,
    MaPLInstruction_uint64_add = 152,
    MaPLInstruction_uint64_subtract = 153,
    MaPLInstruction_uint64_divide = 154,
    MaPLInstruction_uint64_multiply = 155,
    MaPLInstruction_uint64_modulo = 156,
    MaPLInstruction_uint64_bitwise_and = 157,
    MaPLInstruction_uint64_bitwise_or = 158,
    MaPLInstruction_uint64_bitwise_xor = 159,
    MaPLInstruction_uint64_bitwise_negation = 160,
    MaPLInstruction_uint64_bitwise_shift_left = 161,
    MaPLInstruction_uint64_bitwise_shift_right = 162,
    MaPLInstruction_uint64_function_invocation = 163,
    MaPLInstruction_uint64_subscript_invocation = 164,
    MaPLInstruction_uint64_ternary_conditional = 165,
    MaPLInstruction_uint64_typecast = 166,
    
    // CHAR
    MaPLInstruction_char_literal = 167,
    MaPLInstruction_char_variable = 168,
    MaPLInstruction_char_add = 169,
    MaPLInstruction_char_subtract = 170,
    MaPLInstruction_char_divide = 171,
    MaPLInstruction_char_multiply = 172,
    MaPLInstruction_char_modulo = 173,
    MaPLInstruction_char_bitwise_and = 174,
    MaPLInstruction_char_bitwise_or = 175,
    MaPLInstruction_char_bitwise_xor = 176,
    MaPLInstruction_char_bitwise_negation = 177,
    MaPLInstruction_char_bitwise_shift_left = 178,
    MaPLInstruction_char_bitwise_shift_right = 179,
    MaPLInstruction_char_function_invocation = 180,
    MaPLInstruction_char_subscript_invocation = 181,
    MaPLInstruction_char_ternary_conditional = 182,
    MaPLInstruction_char_typecast = 183,

    // VOID
    MaPLInstruction_unused_return_function_invocation = 184,
    MaPLInstruction_char_assign = 185,
    MaPLInstruction_int32_assign = 186,
    MaPLInstruction_int64_assign = 187,
    MaPLInstruction_uint32_assign = 188,
    MaPLInstruction_uint64_assign = 189,
    MaPLInstruction_float32_assign = 190,
    MaPLInstruction_float64_assign = 191,
    MaPLInstruction_boolean_assign = 192,
    MaPLInstruction_string_assign = 193,
    MaPLInstruction_pointer_assign = 194,
    MaPLInstruction_char_assign_subscript = 195,
    MaPLInstruction_int32_assign_subscript = 196,
    MaPLInstruction_int64_assign_subscript = 197,
    MaPLInstruction_uint32_assign_subscript = 198,
    MaPLInstruction_uint64_assign_subscript = 199,
    MaPLInstruction_float32_assign_subscript = 200,
    MaPLInstruction_float64_assign_subscript = 201,
    MaPLInstruction_boolean_assign_subscript = 202,
    MaPLInstruction_string_assign_subscript = 203,
    MaPLInstruction_pointer_assign_subscript = 204,
    MaPLInstruction_char_assign_property = 205,
    MaPLInstruction_int32_assign_property = 206,
    MaPLInstruction_int64_assign_property = 207,
    MaPLInstruction_uint32_assign_property = 208,
    MaPLInstruction_uint64_assign_property = 209,
    MaPLInstruction_float32_assign_property = 210,
    MaPLInstruction_float64_assign_property = 211,
    MaPLInstruction_boolean_assign_property = 212,
    MaPLInstruction_string_assign_property = 213,
    MaPLInstruction_pointer_assign_property = 214,

    // CONTROL FLOW
    MaPLInstruction_conditional = 215,
    MaPLInstruction_cursor_move_forward = 216,
    MaPLInstruction_cursor_move_back = 217,
    MaPLInstruction_program_exit = 218,

    // METADATA
    MaPLInstruction_metadata = 219,

    // DEBUGGING
    MaPLInstruction_debug_line = 220,
    MaPLInstruction_debug_update_variable = 221,
    MaPLInstruction_debug_delete_variable = 222,
    
    // NO-OP
    MaPLInstruction_no_op = 223,
    
    // ERROR CHECKING
    MaPLInstruction_error = 224,
};

#endif /* MaPLBytecodeConstants_h */
